Part 6
kirillovapp/react_shop pull request #6
Opened 2018-09-20 00:12 UTC by kirillovapp

2018-09-20 09:48 UTC, index01d requested changes

2018-09-20 09:48 UTC, index01d commented on src/components/AddToCartButton.js
> +  return {state};
зачем? если не используется

2018-09-20 09:48 UTC, index01d commented on src/components/Cart.js
> +import connect from "react-redux/es/connect/connect";
просто react-redux?

2018-09-20 09:48 UTC, index01d commented on src/components/Cart.js
> +import connect from "react-redux/es/connect/connect";
лучше выделять контейнерный компонент (mapStateToProps, mapActionsToProps и connect()) в отдельный модуль

2018-09-20 09:48 UTC, index01d commented on src/components/Catalog.js
> +          this.props.state.catalog.entries.map((item) => (
нужно передавать не состояние целиком а только нужную часть, тогда здесь не будет такой портянки

2018-09-21 13:37 UTC, index01d requested changes

2018-09-21 13:37 UTC, index01d commented on src/components/CartContainer.js
> +class CartContainer extends Component {
ненужный код на вид?

2018-09-21 13:37 UTC, index01d commented on src/components/CartContainer.js
> +      <Cart cartList = { this.props.cart.entries } />
можно сделать в stateToProps

2018-09-21 13:37 UTC, index01d commented on src/components/CartContainer.js
> +export default connect(mapStateToProps)(CartContainer);
CartContainer -> Cart

2018-09-21 13:37 UTC, index01d commented on src/components/CartCounter.js
> +        <Link to={cartPath()}>В корзине: {this.props.cart.entries.length}</Link>
можно сразу в mapStateToProps сделать нужное значение

2018-09-21 13:37 UTC, index01d commented on src/components/CatalogContainer.js
> +   catalog: state.catalog
.entries

2018-09-21 14:22 UTC, kirillovapp commented on src/components/CartContainer.js
> +export default connect(mapStateToProps)(CartContainer);
@index01d  не понимаю, что нужно сделать. Я вынес mapStateToProps, mapActionsToProps и connect() в CartContainer из Cart, как сделать правильно?

2018-09-22 17:09 UTC, index01d commented on src/components/CartContainer.js
> +export default connect(mapStateToProps)(CartContainer);
у тебя весь смысле компонента CartContainer получился в переименовывании свойства:
```
<Cart cartList = { this.props.cart.entries } />
```

можно с таким же успехом заименовать свойство в mapStateToProps, удалить компонент CartContainer и аргументов в connect подать Cart

2018-09-23 08:08 UTC, index01d approved these changes

2026-07-04 23:47 UTC, closed without merging